version: '3.8'

volumes:
  pg_data:
  static_volume:
  media_volume:
  data_volume:

services:
  db:
    image: postgres:13.10
    env_file:
      - ./.env
    volumes:
    - pg_data:/var/lib/postgresql/data
    - ./init:/docker-entrypoint-initdb.d


  backend:
    image: brriff/foodgram_backend:latest
    volumes:
      - data_volume:/app/data/
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: brriff/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
      - backend